server: 
  port: 9004
spring: 
  application:  
    name: socialWeb-article #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.128:3306/socialWeb_article?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.116.128
  data:
    mongodb:
      host: 192.168.116.128
      database: recruitdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true