server:
  port: 9001
spring:
  application:
    name: socialWeb-base
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.128:3306/socialWeb_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show‐sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true